[package]
name = "egui-glyphon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmic-text = "0.14"
egui = { version = "0.33", default-features = false }
egui-wgpu = { version = "0.33", optional = true }
glyphon = { git = "https://github.com/StratusFearMe21/glyphon", branch = "grezi", optional = true }

[dev-dependencies]
eframe = { version = "0.33", features = ["wgpu"] }
env_logger = "0.11.3"

[features]
default = ["glyphon"]
glyphon = ["dep:glyphon", "dep:egui-wgpu"]
